# Generated by Django 2.2.3 on 2019-09-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultural_events',
            name='fees_amount',
        ),
        migrations.RemoveField(
            model_name='cultural_events',
            name='fees_snu',
        ),
        migrations.RemoveField(
            model_name='cultural_events',
            name='prize_money',
        ),
    ]
