# Generated by Django 2.2.4 on 2019-10-20 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cultural_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, help_text='For SNU niggas only', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cultural_events',
            name='prize_money',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, help_text='For SNU niggas only', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='prize_money',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, help_text='For SNU niggas only', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='prize_money',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='Shiv Nadar University', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
