# Generated by Django 2.2.3 on 2019-10-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191021_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultural_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cultural_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, help_text='For SNU niggas only', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cultural_events',
            name='prize_money',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sports_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, help_text='For SNU niggas only', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='prize_money',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
