# Generated by Django 2.2.3 on 2019-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20191026_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('event_name', models.PositiveIntegerField()),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Event_Registrations',
            },
        ),
    ]
