# Generated by Django 2.2.3 on 2019-10-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registrations',
            name='event_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_registrations',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
    ]
