# Generated by Django 2.2.3 on 2019-11-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20191108_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultural_events',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='sports_events',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='technical_events',
            name='team_size',
        ),
        migrations.AddField(
            model_name='cultural_events',
            name='team_size_max',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='cultural_events',
            name='team_size_min',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='event_registrations',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='team_size_max',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='team_size_min',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='team_size_max',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='team_size_min',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cultural_events',
            name='poster',
            field=models.ImageField(help_text='Poster file', null=True, upload_to='static/static_dirs/images/'),
        ),
        migrations.AlterField(
            model_name='sports_events',
            name='poster',
            field=models.ImageField(help_text='Poster file', null=True, upload_to='static/static_dirs/images/'),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='poster',
            field=models.ImageField(help_text='Poster file', null=True, upload_to='static/static_dirs/images/'),
        ),
    ]
