# Generated by Django 2.2.6 on 2019-11-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20191119_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registrations',
            name='paid',
            field=models.CharField(default='Unpaid', help_text='Paid,Verification pending or Unpaid.If verified change to paid', max_length=25),
        ),
    ]
