# Generated by Django 2.2.3 on 2019-11-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20191119_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical_events',
            name='category',
            field=models.CharField(help_text='Examples: music,dance', max_length=100, null=True),
        ),
    ]
