# Generated by Django 2.2.6 on 2019-11-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_technical_events_category'),
        ('events', '0014_auto_20191120_0031'),
    ]

    operations = [
    ]
