# Generated by Django 2.2.3 on 2019-11-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_merge_20191122_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural_events',
            name='sheet_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event_registrations',
            name='payment_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='sheet_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='sheet_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cultural_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, help_text='For SNU only', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sports_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, help_text='For SNU only', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, help_text='For SNU only', max_digits=6, null=True),
        ),
    ]
