# Generated by Django 2.2.3 on 2019-11-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20191125_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('uuid', models.CharField(max_length=300, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('events', models.CharField(max_length=1000)),
                ('payment_string', models.CharField(max_length=200, null=True)),
                ('partial', models.BooleanField(default=False)),
                ('fullAmount', models.PositiveIntegerField(null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('paid', models.CharField(default='Verification Pending', help_text='Verification Pending or Paid. If verified change to paid', max_length=25)),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
