# Generated by Django 2.2.3 on 2019-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='college',
            field=models.CharField(default='Shiv Nadar University', max_length=1000),
        ),
    ]
