# Generated by Django 2.2.3 on 2019-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_payment_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registrations',
            name='payment_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
