# Generated by Django 2.2.3 on 2019-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20191125_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
