# Generated by Django 2.2.3 on 2019-11-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports_events',
            name='form_array',
            field=models.TextField(default=''),
        ),
    ]
