# Generated by Django 2.2.3 on 2019-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_sports_events_form_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports_events',
            name='prize_money',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
