# Generated by Django 2.2.3 on 2019-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20191126_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports_events',
            name='category',
            field=models.CharField(help_text='Examples: music,dance', max_length=100, null=True),
        ),
    ]
