# Generated by Django 2.2.3 on 2019-11-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_sports_events_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultural_events',
            name='perperson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_registrations',
            name='numberofpeople',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event_registrations',
            name='perperson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='perperson',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='perperson',
            field=models.BooleanField(default=False),
        ),
    ]
