# Generated by Django 2.2.3 on 2019-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20191127_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultural_events',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cultural_events',
            name='rules',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sports_events',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sports_events',
            name='rules',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='rules',
            field=models.TextField(null=True),
        ),
    ]
