# Generated by Django 2.2.3 on 2020-01-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20200103_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical_events',
            name='form_array',
        ),
        migrations.AddField(
            model_name='cultural_events',
            name='offsite_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cultural_events',
            name='offsite_register_link',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='offsite_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sports_events',
            name='offsite_register_link',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='offsite_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technical_events',
            name='offsite_register_link',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='cultural_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cultural_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cultural_events',
            name='prize_money',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sports_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sports_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sports_events',
            name='prize_money',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='fees_snu',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='technical_events',
            name='prize_money',
            field=models.TextField(null=True),
        ),
    ]
