# Generated by Django 2.2.7 on 2020-01-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20200112_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical_events',
            name='form_array',
            field=models.TextField(default=''),
        ),
    ]
