# Generated by Django 2.2.3 on 2020-01-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_technical_events_form_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('start_date', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('1', '1 day'), ('2', '2 days'), ('3', '3 days')], max_length=1)),
                ('include_food', models.BooleanField(default=False)),
                ('mobile_no', models.CharField(help_text='Contact number of guests ', max_length=100, null=True)),
                ('number_of_people', models.IntegerField(default=1)),
                ('paid', models.CharField(default='Unpaid', help_text='Paid,Verification pending or Unpaid.If verified change to paid', max_length=25)),
            ],
        ),
    ]
