# Generated by Django 2.2.3 on 2020-01-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_accommodation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accommodation',
            table='Accommodation',
        ),
    ]
