# Generated by Django 2.2.3 on 2020-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20200120_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='include_food',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.CharField(choices=[('1', '1 day'), ('2', '2 days'), ('3', '3 days'), ('4', '4 days')], max_length=10),
        ),
    ]
