# Generated by Django 2.2.3 on 2020-01-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20200120_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='college',
        ),
    ]
