# Generated by Django 2.2.7 on 2020-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_remove_accommodation_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='college',
            field=models.CharField(default='Shiv Nadar University', max_length=100),
        ),
    ]
